image: ilssim/cmake-boost-qt5

build:
  stage: build
  script:
    - pushd QtWebApp
    - mkdir build
    - pushd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - mkdir root
    - make DESTDIR=root install
    - pushd root
    - tar cf ../qtwebapp.tar *
    - popd # root
    - xz qtwebapp.tar
    - popd # build
    - popd # QtWebApp
    - mv QtWebApp/build/qtwebapp.tar.xz .
  artifacts:
    paths:
      - qtwebapp.tar.xz

test:
  stage: test
  script:
    - xz -d qtwebapp.tar.xz
    - tar xf qtwebapp.tar -C /
    - pushd Demo1
    - mkdir build
    - cd build
    - cmake ..
    - make
    - popd # Demo1
    - pushd Demo2
    - mkdir build
    - cd build
    - cmake ..
    - make
    - popd # Demo2
    - mv Demo1/build/demo1 Demo2/build/demo2 .
  artifacts:
    paths:
      - demo1
      - demo2
