language: c++

matrix:
    include:
        - os: linux
          compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-4.8
                      - g++-4.8

# disable clang because of bugs in qt 5.0.2
#        - os: linux
#          compiler: clang
#          addons:
#              apt:
#                  sources:
#                      - llvm-toolchain-precise-3.7
#                  packages:
#                      - clang-3.7
    
sudo: false
addons:
    apt:
        sources:
            - ubuntu-sdk-team
        packages:
            - qt5-qmake
            - qtbase5-dev
            - qtdeclarative5-dev
            - libqt5webkit5-dev
            - libsqlite3-dev

#before_install:
#    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
#    - sudo apt-get update -qq
#    - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev

script:
    - qmake -qt=qt5 -v
    - echo CC=$CC
    - test $CC = clang \
        && qmake -qt=qt5 -spec linux-clang QMAKE_CXX=clang++-3.7 QMAKE_CC=clang-3.7 \
        || qmake -qt=qt5 -spec linux-g++ QMAKE_CXX=g++-4.8 QMAKE_CC=gcc-4.8
    - make
