language: c++
sudo: required
dist: precise

compiler: gcc

addons:
    apt:
        sources:
          - kalakris-cmake
          - sourceline: 'ppa:immerrr-k/qt5-backport'
        packages:
          - cmake
          - debhelper
          - dpkg-dev
          - qtbase5-dev-tools

script:
# try to compile at "as it is"
  - pushd QtWebApp
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - popd
# and then try to compile it as a debian package
  - dpkg-buildpackage -us -uc
  - ls ../libqtwebapp*
