language: c++
sudo: required
dist: precise

compiler:
 - gcc
 - clang

addons:
    ssh_known_hosts: msrd0.duckdns.org
    apt:
        sources:
          - kalakris-cmake
          - sourceline: 'ppa:immerrr-k/qt5-backport'
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - cmake
          - g++-5
          - gcc-5
          - qtchooser
          - qt5-default

before_install:
  - test $CC  == gcc && export CC=/usr/bin/gcc-5
  - test $CXX == g++ && export CXX=/usr/bin/g++-5
  - $CC --version
  - $CXX --version

script:
  - pushd QtWebApp
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - popd
