language: c++
sudo: required
dist: precise

compiler: gcc

addons:
    apt:
        sources:
          - kalakris-cmake
          - sourceline: 'ppa:immerrr-k/qt5-backport'
        packages:
          - apt-utils
          - cmake
          - debhelper
          - dpkg-dev
          - qtchooser
          - qt5-default

before_script:
  - openssl aes-256-cbc -K $encrypted_f039ccdac5d1_key -iv $encrypted_f039ccdac5d1_iv -in .travis/alarmpi-debian.enc -out .travis/alarmpi-debian -d
  - openssl aes-256-cbc -K $encrypted_f039ccdac5d1_key -iv $encrypted_f039ccdac5d1_iv -in .travis/alarmpi-debian.pub.enc -out .travis/alarmpi-debian.pub -d
  - mv .travis/alarmpi-debian* ~/.ssh/
  - echo "Host msrd0.duckdns.org" >>~/.ssh/config
  - echo "  IdentityFile ~/.ssh/alarmpi-debian" >>~/.ssh/config

script:
# try to compile "as it is"
  - pushd QtWebApp
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - popd
# and then try to compile it as a debian package
  - dpkg-buildpackage -us -uc
  - ls ../libqtwebapp*

after_success:
  - mkdir mount
  - sshfs alarmpi-debian@msrd0.duckdns.org:/srv/debian mount
  - rm mount/pool/main/all/libq/libqtwebapp* mount/pool/main/amd64/libq/libqtwebapp*
  - cp ../libqtwebapp*all*.deb mount/pool/main/all/libq/
  - cp ../libqtwebapp*amd64*.deb mount/pool/main/amd64/libq/
  - mount/bin/genpackages.sh mount
  - mount/bin/genrelease.sh mount
  - ssh alarmpi-debian@msrd0.duckdns.org /srv/debian/bin/sign.sh
  - sudo umount mount

after_script:
  - rm ~/.ssh/alarmpi-debian*
