language: c++
sudo: required
dist: precise

compiler:
 - gcc
 - clang

addons:
    ssh_known_hosts: msrd0.duckdns.org
    apt:
        sources:
          - kalakris-cmake
          - sourceline: 'ppa:immerrr-k/qt5-backport'
        packages:
          - cmake
          - qtchooser
          - qt5-default

script:
  - pushd QtWebApp
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - popd
