language: c++
sudo: required
dist: precise

compiler: gcc

env:
  - LD_LIBRARY_PATH=/usr/local/lib

addons:
    ssh_known_hosts: msrd0.duckdns.org
    apt:
        sources:
          - kalakris-cmake
          - sourceline: 'ppa:immerrr-k/qt5-backport'
        packages:
          - apt-utils
          - cmake
          - debhelper
          - dpkg-dev
          - qtchooser
          - qt5-default
          - sshfs

before_script:
  - dig +short myip.opendns.com @resolver1.opendns.com
  - openssl aes-256-cbc -K $encrypted_f039ccdac5d1_key -iv $encrypted_f039ccdac5d1_iv -in .travis-keys.tar.xz.enc -out .travis-keys.tar.xz -d
  - tar xfa .travis-keys.tar.xz
  - mv alarmpi-debian* ~/.ssh/
  - touch ~/.ssh/config
  - echo "Host msrd0.duckdns.org" >>~/.ssh/config
  - echo "  IdentityFile ~/.ssh/alarmpi-debian" >>~/.ssh/config


script:
  - version=$(cat debian/changelog | grep -E '^intranet \(.+\) precise' | head -n1 | tr -d '(' | tr '-' ' ' | awk '{print $2}')
  - echo "QSL $version"
  - wget "https://msrd0.duckdns.org/git/msrd0/KFG-Intranet/archive/v${version}.tar.gz"
  - tar xfz "v${version}.tar.gz"
  - pushd "kfg-intranet"
  - cp -R ../debian .
  - dpkg-buildpackage -us -uc
  - popd
  - ls libqtwebapp*

after_success:
  - make
  - test -d mount && sudo umount mount || true

after_script:
  - rm ~/.ssh/alarmpi-debian*
